### ISSUE TITLE
Опис вимог до проекту

### ISSUE THREAD

**Issue by KrisstinaL** [SoftwareEngineering-20-21/SuperCalendar#1]
Описати основні функціональні та нефункціональні вимоги до проекту.

**Comment by KrisstinaL** [comment]
UserStory.md

**Comment by KrisstinaL** [comment]
[UserStory.md](url)

**Comment by KrisstinaL** [comment]
[https://github.com/SoftwareEngineering-20-21/SuperCalendar/blob/master/UserStory.md](url)

**Comment by KrisstinaL** [comment]
`UserStory.md`

**Comment by KrisstinaL** [comment]
[https://github.com/SoftwareEngineering-20-21/SuperCalendar/blob/master/UserStory.md](url)

**Comment by ShevHK** [comment]
Завдання виконано.
