### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by KrisstinaL** [SoftwareEngineering-20-21/SuperCalendar#3]
До кожної сторінки аплікації створити Wireframes, використовуючи один з інструментів (типу balsamiq).

**Comment by natalistruk** [comment]
[wireframes.pdf](https://github.com/SoftwareEngineering-20-21/SuperCalendar/files/5311597/wireframes.pdf)

**Comment by IrynaSt1** [comment]
Good job!!!
